language: rust
after_success: |-
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  echo "shynd.xyz" > target/doc/CNAME &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: du01AsCusNRJ8OZb07QNCngfoAZ7mZ+zZ2Iou6HlTwgo1EmPTFLLHdWkUPaU/Y+HrjFQr8qqc53xvBxubGL2OYf2CPHt14J9h0YhcmWe7tN0sihfBTm5KgVWME6XEvI0eThWdUjxytR6np5uip/5HXOidtg6CEkuC39cRNYLqZjzPkDwYuzbG7dHi4r8M0OkcNZKCGBUWJyPMkgyjzNrsz4UrUBGXbZ+S2aViGj+SnuiiFA8dxXKv+uEjVM1czHy3dH8/eeQQMKP42V2GIGp4clK+W4IulMlKME5bChuzQRausuZRPHZQEE2CUuFDR79jzSVfBIPz7C3o3XYuzP7MevCkh0XCmfyi7/G+JzGjcabgrydzbRAhOx9a2zrByL+YADPsM4+hBPT4ZAvG09TN8oe+XZ7lmk3HrYOkpe3AsuadP4/5QiWG7ynoQIdmd80MpWDyJnBGQ6XzDHynbNaHc6ffwREU8gO7Fw4ulEifvmZVw/f4WPOUL6X6S30q+Q0ffQYfMZ/oLWO3N0FLqrw2EGWahwfveSHPlmkli34wKX8bJnhXwqcahvEcxsNLD4xJJPlJv0l9gKOVxkNU9EhhV4lAlf629XOF7Z0ueybp0JVGwggaC6YTXBbKf3heuquHJLJ/bL0XLiLB0gasfq3B+MrCbEz8Fk9aHLKMRN14FE=
notifications:
  slack:
    rooms:
      secure: xReH0SvzITa1ZwosA4cKsCKtQg0hTg2Bl7aSSnzSDpNdPQkxO5p6ve7jhqyB26vhEdv2a/aji5M3epYFY+UUGTCNS5f2NJzRCoyi0sON4nOb6DmOAXtiFVnVjarfj1uokurAYFak4AIKQihpU79DH4v2ftnTl5by5QdL1nLIfgGxckE4OH780WWcsmHfAhhA+AZeYE6AuH/IiheCWtiy/WrwYKAMkpRcaO2i+wkffnctHUT9dUYTBoJg13uXGlI83dZN2o3X53iEeLMj7yFW/BRRKx4Qg76nAxSOvYx1nwOmeCJLWAaAjtXxa1WmB1u1Gx5bCNtcXTvOIgsct/bVsRYd1Gst1J5U/XL+zJpYXGQ6LvAtqX3vhtpQWJrjwy38bAAnmSJE1J/bZdx5lslyoCzpI3yXXxj/6nsO/SEbdncfTWlhlrZH3E3d2xE/0KUFZt7oYEKngudumznwnLvRMUuZKzsv2oIDxAjgY7Kx0BVg25btO3S95k9Kq4yroCxarHQ59ODDIC7GAul07DSMXHhtc4oBuz/c4S0/YRe2s6X2hx4gpDtY5rVBF2G23tiZBJwezEN4EbYUaGrULzFhkq+1nls/+Zq7C7TfMYCrZ0pt76Hm0/2BYWxZeqgL0y10gBGWUWvO+BHqmi9FbgUqnXe6mez9GTcJ7jWIHALYBuA=
